# Generated by Django 4.2.11 on 2024-05-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_type', models.CharField(choices=[('personal', 'Личный'), ('organizational', 'Организационный')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('account_creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisites_monobank_jar', models.CharField(max_length=255)),
                ('requisites_iban', models.CharField(max_length=255)),
                ('requisites_paypal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_expected_due_date', models.DateTimeField(null=True)),
                ('donation_requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.donationrequisites')),
            ],
        ),
        migrations.CreateModel(
            name='DonationTargetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationTargetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('files', models.BinaryField(null=True)),
                ('donation_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.donationtarget')),
            ],
        ),
        migrations.AddField(
            model_name='donationtarget',
            name='donation_target_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.donationtargetreport'),
        ),
        migrations.AddField(
            model_name='donationtarget',
            name='donation_target_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.donationtargetstatus'),
        ),
        migrations.AddField(
            model_name='donationtarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
