# Generated by Django 4.2.11 on 2024-05-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grantweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('actual_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.BinaryField(null=True)),
                ('description', models.TextField()),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.messenger')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.role')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.userprofile')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.usertype')),
            ],
        ),
        migrations.AlterField(
            model_name='donationtarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantweb.user'),
        ),
    ]
